dekoding_test/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('root.urls')),
    path('admin/', admin.site.urls),
]

root/urls.py
from django.urls import path

from .views import (
    IndexView,
    FrontendView,
    BackendView,
    CreateDog,
    ListDog,
    Front2View,
    Back2View,
    get_git_users,
)


urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('frontend/', FrontendView.as_view(), name="frontend"),
    path('backend/', BackendView.as_view(), name="backend"),
    path('backend/dog/add/', CreateDog.as_view(), name='add-dog'),
    path('backend/dog/list/', ListDog.as_view(), name='list-dog'),
    path('frontend/2/', Front2View.as_view(), name='front2'),
    path('backend/2', Back2View.as_view(), name='back2'),
    path('get_git_user/', get_git_users, name='get_git_user'),
]

root/models.py
from django.db import models


class OwnerModel(models.Model):
    name = models.CharField(max_length=120)
    address = models.TextField(null=True, blank=True)
    number = models.CharField(max_length=9, null=True, blank=True)

    def __str__(self):
        return self.name


class DogModel(models.Model):
    name = models.CharField(max_length=45)
    age = models.SmallIntegerField()
    breed = models.CharField(max_length=45)
    owner = models.ForeignKey(OwnerModel, on_delete=models.CASCADE,
                              null=True, blank=True)

    def __str__(self):
        return self.name

root/forms.py
from django import forms
from .models import DogModel


class DogForm(forms.ModelForm):
    class Meta:
        model = DogModel
        fields = '__all__'

root/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.generic import View, CreateView, ListView
from django.core import serializers
from .models import DogModel
from .forms import DogForm
import requests as res
import json


class IndexView(View):
    template_name = "index.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class FrontendView(View):
    template_name = "frontend.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class BackendView(View):
    template_name = "backend.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class CreateDog(CreateView):
    model = DogModel
    success_url = reverse_lazy('list-dog')
    template_name = 'add_dog.html'
    form_class = DogForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selected'] = 'add-dog'
        return context


class ListDog(ListView):
    model = DogModel
    template_name = 'list_dog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['selected'] = 'list-dog'
        return context


class Front2View(View):
    template_name = "frontend2.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class Back2View(View):
    template_name = 'backend2.html'

    def get(self, request):
        search = request.GET.get('search', None)
        context = dict()
        if search:
            url = 'https://api.github.com/search/users?q={0}&per_page=20'.\
                format(search)
            r = res.get(url)
            if r.status_code == 200:
                data = r.json()
                if data['total_count'] > 0:
                    objects = data['items']
                    for obj in objects:
                        extra = res.get(obj['url'])
                        obj['more'] = extra.json()
                    context['objects'] = objects
        return render(request, self.template_name, context)


def get_git_users(request):
    search = request.GET.get('search', None)
    data = dict()
    if search:
        url = 'https://api.github.com/search/users?q={0}&per_page=5'. \
            format(search)
        r = res.get(url)
        if r.status_code == 200:
            objects = r.json()
            if objects['total_count'] > 0:
                data = objects['items']
                print(type(data))
    return JsonResponse(data, safe=False)

templates/add_dog.html
{% extends "backend.html" %}
{% load static %}

{% block content_2 %}
  <div class="border rounded-55 py-3 bg-purple back-title">
    <h3 class="pl-4">Add Dog</h3>
  </div>
  <div>
    <form method="post" class="mt-5 pb-3">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control input-border-bottom" id="id_name" name="name" placeholder="Name">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md">
          <input type="text" class="form-control input-border-bottom" id="id_breed" name="breed" placeholder="Breed">
        </div>
        <div class="form-group col-md">
          <input type="number" class="form-control input-border-bottom" id="id_age" name="age" placeholder="Age">
        </div>
        <div class="form-group col-md">
          <select class="form-control input-border-bottom" name="owner" id="id_owner">
            <option value="" selected="">Owner</option>
            {% for option in form.fields.owner.choices.queryset %}
              <option value="{{ option.id }}">{{ option }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <button type="submit" class="btn btn-primary btn-sm border rounded-55 px-4 py-1 bg-purple mt-4">
        <span class="small">SAVE DOG</span>
      </button>
    </form>
  </div>
{% endblock %}

templates/backend.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container-fluid">
    <div class="row" style="height: 100vh">
      <div class="col-md-2 bg-black text-white">
        <div class="border-bottom border-white">
          <div class="p-3 d-table">
            <p class="float-left d-table-cell align-middle m-0 mr-2"><img class="img-fluid" src="{% static 'images/small_logo.png' %}"></p>
            <p class="d-table-cell align-middle">DEKODING</p>
          </div>
        </div>
        <div class="list-group mt-4 text-white">
          <a href="{% url 'list-dog' %}" class="list-group-item item-nav {% if selected == 'list-dog' %}selected{% endif %}">
            <img src="{% static 'images/list_icon.png' %}" class="mr-2" >
            <span>Dog List</span>
          </a>
          <a href="{% url 'add-dog' %}" class="list-group-item item-nav {% if selected == 'add-dog' %}selected{% endif %}">
            <img src="{% static 'images/add_icon.png' %}" class="mr-2" >
            <span>Add Dog</span>
          </a>
          <a href="#" class="list-group-item item-nav">
            <img src="{% static 'images/list_icon.png' %}" class="mr-2" >
            <span>Owner List</span>
          </a>
          <a href="#" class="list-group-item item-nav">
            <img src="{% static 'images/add_icon.png' %}" class="mr-2" >
            <span>Add Owner</span>
          </a>
        </div>
      </div>
      <div class="col-md-10 pt-5" style="background-color: #EDEDED">
        <div class="container mt-5 bg-white rounded rounded-55">
          {% block content_2 %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/backend2.html
{% extends "backend.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/easy-autocomplete.css' %}">
  <link rel="stylesheet" href="{% static 'css/easy-autocomplete.themes.css' %}">
{% endblock %}
{% block content_2 %}
  <div class="border rounded-55 py-3 bg-purple back-title">
    <h3 class="pl-4">List Git</h3>
  </div>
  <form method="get">
    {% csrf_token %}
    <div class="form-row">
      <div class="col-md-4 easy-autocomplete">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search" id="search">
      </div>
      <div class="col-md-2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </div>
    </div>
  </form>
  <div class="mt-5 pb-3">
    {% if objects %}
      <table class="table">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Username</th>
          <th scope="col">Repository</th>
          <th scope="col">Followers</th>
          <th scope="col">Following</th>
        </tr>
        </thead>
        <tbody>
        {% for object in objects %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ object.login }}</td>
            <td><i class="fab fa-github" onclick="location.href='{{ object.html_url }}'"></i></td>
            <td>{{ object.more.followers }}</td>
            <td>{{ object.more.following }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h6>No matches</h6>
    {% endif %}
  </div>
{% endblock %}

{% block extra_js %}
  <script src="{% static 'js/jquery.easy-autocomplete.js' %}"></script>
  <script src="{% static 'js/search_suggestions.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dekoding Test</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'index' %}">
    <img src="{% static 'images/dekoding_logo.png' %}" class="img-fluid" width="100px">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% block content %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

templates/frontend.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="50000">
    <div class="carousel-inner">
      <div class="carousel-item slider active">
        <div class="d-flex h-100 text-center" style="background:#606060;">
          <img class="align-self-center w-50 mx-auto" src="{% static 'images/logo.png' %}" alt="First slide">
        </div>
      </div>
      <div class="carousel-item slider">
        <div class="row h-100">
          <div class="col-md-4 d-table h-50 text-center" style="background-color: #00A6E3">
            <h1 class="d-table-cell align-middle" style="font-size: 10em">D</h1>
          </div>
          <div class="col-md-4 d-table h-50 text-center" style="background-color: #0065BB">
            <h1 class="d-table-cell align-middle" style="font-size: 10em">E</h1>
          </div>
          <div class="col-md-4 d-table h-50 text-center" style="background-color: #3B0090">
            <h1 class="d-table-cell align-middle" style="font-size: 10em">K</h1>
          </div>
          <div class="col-md-12 d-table h-50 text-center" style="background-color: #554842">
            <h1 class="d-table-cell align-middle" style="font-size: 10em">ODING</h1>
          </div>
        </div>
      </div>
      <div class="carousel-item slider">
        <div class="h-100 row d-flex align-items-end" style='background-image: url("{% static 'images/wallpaper.png' %}")'>
          <div class="offset-md-7 col-md-4 text-right mb-5 pr-2">
            <div class="bg-primary rounded rounded-55" style="height: 10rem">
              <h3 class="card-title text-white text-center pt-3">Dekoding</h3>
            </div>
            <button type="button" class="btn btn-primary btn-sm rounded rounded-55 px-4 my-3" data-toggle="modal" data-target="#exampleModal">
              Submit
            </button>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev" style="width: 5%">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next" style="width: 5%">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Content Content
        </div>
        <div class="modal-footer">
          <button id="btn-close" type="button" class="btn btn-secondary d-none">Close</button>
          <button id="btn-submit" type="button" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block extra_js %}
  <script>
      (function ($) {
          var btn_close = $('#btn-close');
          var btn_submit = $('#btn-submit');
          btn_submit.on('click', function () {
              btn_close.removeClass('d-none')
          });
          btn_close.on('click', function () {
              $(this).addClass('d-none')
          })
      })(jQuery);
  </script>
{% endblock %}

templates/frontend2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>INICIO - RANKANA - Zeplin</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="{% static 'css/front2.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid px-0">
  <!-- Navbar -->
  <nav class="navbar navbar-light bg-white">
    <div class="row w-100 border-bottom px-content py-3">
      <div class="col-md-4">
        <a class="navbar-brand" href="#">
          <img src="{% static 'images/front2/black-rec.png' %}" class="img-fluid rect-black">
          <img src="{% static 'images/front2/logo.png' %}" class="d-inline-block align-top img-logo" alt="">
          <img src="{% static 'images/front2/logo-name.png' %}" class="img-logo-name">
        </a>
      </div>
      <div class="offset-md-2 col-md-6">
        <div class="row">
          <div class="offset-md-4 col-md-2 text-center">
            <small class="">Register</small>
          </div>
          <div class="col-md-2 text-center border-left border-right">
            <small class="">Login</small>
          </div>
          <div class="col-md-2 text-center">
            <small class="text-yellow-brown">
              EN <i class="fas fa-chevron-down ml-3"></i>
            </small>
          </div>
          <div class="col-md-2 text-center">
            <i class="fas fa-bars"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="row w-100 px-content py-1">
      <div class="offset-md-2 col-md-10">
        <div class="row">
          <div class="offset-md-4 col-md-2 p-0 text-center border-right">
            <i class="fas fa-filter"></i> <small class="font-weight-bold">Artisans catalog</small>
          </div>
          <div class="col-md-6 p-0 text-left pl-2">
            <ul class="list-inline">
              <li class="list-inline-item"><small class="text-muted">Goldsmithing</small></li>
              <li class="list-inline-item"><small class="text-muted">Paints</small></li>
              <li class="list-inline-item"><small class="text-muted">Tapestry</small></li>
              <li class="list-inline-item"><small class="text-muted">Hangbags</small></li>
              <li class="list-inline-item"><small class="text-muted">Ceramic</small></li>
              <li class="list-inline-item"><small class="text-muted">Textil</small></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- Slider -->
  <div id="carouselExampleIndicators" class="carousel slide mt-less-15" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/front2/banner.jpg' %}" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="caption-carousel between-lines">We share customs</h1>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev w-10" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next w-10" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!--Home side -->
  <div class="row border-bottom px-content">
    <div class="col-md-12 position-relative" style="bottom: -12px">
      <ul class="list-inline">
        <li class="list-inline-item text-yellow-brown"><small class="font-weight-bold">HOME</small></li>
        <li class="list-inline-item"><img src="{% static 'images/front2/right_row.png' %}" class="img-fluid w-50"></li>
        <li class="list-inline-item"><small class="">WHAT IS RANKANA</small></li>
      </ul>
    </div>
  </div>
  <div class="row px-content">
    <div class="col-md-4">
      <img src="{% static 'images/front2/person.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4 text-center py-5">
      <h3 class="font-weight-bold">What is Rankana?</h3>
      <p>We are not a conventional e commerce</p>
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/computer.png' %}" class="img-fluid">
    </div>
  </div>
  <div class="row position-relative rectangle">
    <div class="col-md-12">
      <img src="{% static 'images/front2/rectangle.png' %}" class="img-fluid">
    </div>
  </div>
  <!-- Images -->
  <div class="row px-content">
    <div class="col-md-4">
      <img src="{% static 'images/front2/cuadro_ejemplo.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/2.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/3.png' %}" class="img-fluid">
    </div>
  </div>
  <div class="row px-content mt-2">
    <div class="col-md-4">
      <img src="{% static 'images/front2/4.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/5.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/6.png' %}" class="img-fluid">
    </div>
  </div>
  <div class="row px-content mt-2 mb-5">
    <div class="col-md-4">
      <img src="{% static 'images/front2/7.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/8.png' %}" class="img-fluid">
    </div>
    <div class="col-md-4">
      <img src="{% static 'images/front2/9.png' %}" class="img-fluid">
    </div>
  </div>
  <!-- Categories -->
  <div class="bg-gray mt-5 py-5">
    <div class="row px-content">
      <div class="col-md-12 text-center my-5">
        <h3 class="font-weight-bold dark between-lines">Our Product Categories</h3>
        <p class="text-muted">Navigate and discover unique products</p>
      </div>
    </div>
    <div class="row px-content my-3">
      <div class="col-md-4 text-center">
        <img src="{% static 'images/front2/category1.png' %}" class="img-fluid w-25">
      </div>
      <div class="col-md-4 text-center">
        <img src="{% static 'images/front2/category2.png' %}" class="img-fluid w-25">
      </div>
      <div class="col-md-4 text-center">
        <img src="{% static 'images/front2/category3.png' %}" class="img-fluid w-25">
      </div>
    </div>
    <div class="row px-content my-4">
      <div class="col-md-4 text-center">
        <h6 class="font-weight-bold">Goldsmithing</h6>
      </div>
      <div class="col-md-4 text-center border-dark border-left border-right">
        <h6 class="font-weight-bold">Paints</h6>
      </div>
      <div class="col-md-4 text-center">
        <h6 class="font-weight-bold">Tapestry</h6>
      </div>
    </div>
    <div class="row px-content my-5">
      <div class="col-md-3 text-center">
        <img src="{% static 'images/front2/category4.png' %}" class="img-fluid w-25">
      </div>
      <div class="col-md-3 text-center">
        <img src="{% static 'images/front2/category5.png' %}" class="img-fluid w-25">
      </div>
      <div class="col-md-3 text-center">
        <img src="{% static 'images/front2/category6.png' %}" class="img-fluid w-25">
      </div>
      <div class="col-md-3 text-center">
        <img src="{% static 'images/front2/category7.png' %}" class="img-fluid w-15">
      </div>
    </div>
    <div class="row px-content">
      <div class="col-md-3 text-center">
        <h6 class="font-weight-bold">Compas</h6>
      </div>
      <div class="col-md-3 text-center border-dark border-left border-right">
        <h6 class="font-weight-bold">Hangbags</h6>
      </div>
      <div class="col-md-3 text-center border-dark border-right">
        <h6 class="font-weight-bold">Ceramic</h6>
      </div>
      <div class="col-md-3 text-center">
        <h6 class="font-weight-bold">Textile</h6>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="bg-black py-5">
    <div class="row px-content">
      <div class="col-md-2">
        <h6 class="text-yellow-brown">PRODUCT LINE</h6>
        <ul>
          <li>Goldsmithing</li>
          <li>Paints</li>
          <li>Tapestry</li>
          <li>Compas</li>
          <li>Handbags</li>
          <li>Ceramic</li>
          <li>Textile</li>
        </ul>
      </div>
      <div class="col-md-2">
        <h6 class="text-yellow-brown">RANKANA</h6>
        <ul>
          <li>About us</li>
          <li>Mission & Vision</li>
          <li>Product line</li>
        </ul>
      </div>
      <div class="col-md-2">
        <h6 class="text-yellow-brown">CONTACT US</h6>
        <ul>
          <li>Register</li>
          <li>Login</li>
          <li>Contact us</li>
          <li>Phone number</li>
          <li>E-mail</li>
        </ul>
      </div>
      <div class="offset-md-3 col-md-3 text-center">
        <h6 class="text-yellow-brown">FOLLOW US ON</h6>
        <ul class="list-inline">
          <img src="{% static 'images/front2/fae.png' %}" class="img-fluid w-15 mx-1">
          <img src="{% static 'images/front2/tw.png' %}" class="img-fluid w-15 mx-1">
          <img src="{% static 'images/front2/ins.png' %}" class="img-fluid w-15 mx-1">
        </ul>
      </div>
    </div>
    <div class="row px-content">
      <div class="col-md-12 text-center text-cold-gray">
        @copyright-2018-rankana-all-rights-reserved-data-privacy
      </div>
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Dekoding Test</h1>
        <p>This tests is all about testing your skills as Frontend and Backend developer, you should implement the tasks mentioned on the
          description of the test on the following views using bootstrap as UI.</p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-3">
          <h2>Frontend</h2>
          <p>We are going to test if you can create user interfaces according to the design sent.</p>
          <p><a class="btn btn-secondary" href="{% url 'frontend' %}" role="button">Lets do it »</a></p>
        </div>
        <div class="col-md-3">
          <h2>Backend</h2>
          <p>We are going to test if you can implement new functionalities to projects.</p>
          <p><a class="btn btn-secondary" href="{% url 'list-dog' %}" role="button">Lets do it »</a></p>
        </div>
        <div class="col-md-3">
          <h2>FrontEnd 2</h2>
          <p><a class="btn btn-secondary" href="{% url 'front2' %}" role="button">Lets do it »</a></p>
        </div>
        <div class="col-md-3">
          <h2>BackEnd 2</h2>
          <p><a class="btn btn-secondary" href="{% url 'back2' %}" role="button">Lets do it »</a></p>
        </div>
      </div>
      <hr>
    </div> <!-- /container -->
  </main>
{% endblock %}

templates/list_dog.html
{% extends "backend.html" %}
{% load static %}

{% block content_2 %}
  <div class="border rounded-55 py-3 bg-purple back-title">
    <h3 class="pl-4">Dogs List</h3>
  </div>
  <div class="mt-5 pb-3">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Breed</th>
        <th scope="col">Owner</th>
      </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object.name|capfirst }}</td>
          <td>{{ object.age }}</td>
          <td>{{ object.breed|capfirst }}</td>
          <td>{{ object.owner }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}